CREATE TABLE IF NOT EXISTS tmp (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ingested_at timestamp DEFAULT CURRENT_TIMESTAMP,
    data json NOT NULL
);
CREATE TABLE IF NOT EXISTS pws (
	"OxfordStudyEntityId" text, 
    "EventName" text,
   	"EntityType" text, 
    "EventId" text,
    "EntityId" text,
    "LevelProgressionAmount" real,
    "CurrentJobName" text,
    "CurrentSessionLength" int,
    "CurrentCreditAmount" real,
    "CampaignProgressionAmount" real,
    "CurrentCareerJobsInProgress" text[],
    "CurrentFreeplayJobsInProgress" text[],
    "CurrentSpecialJobsInProgress" text[],
    "CurrentChallengeJobsInProgress" text[],
    "CurrentGameMode" text,
    "LastItemPurchased" text,
    "LastTaskCompleted" text,
    "LastSubtaskCompleted" text,
    "LastJobCompleted" text,
    "MultiplayerMode" text,
    "CurrentLanguage" text,
    "CumulativeTimeSpentInLevel" text,
    "CrouchState" text,
    "CurrentPosition" text,
    "CurrentNozzle" text,
    "CurrentWasher" text,
    "CurrentExtension" text,
    "LastStudyPromptType" text,
    "Timestamp" timestamp
);
CREATE TABLE pws_s3 AS 
TABLE pws 
WITH NO DATA;